//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qr_shp_Log
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rawscaEntities : DbContext
    {
        public rawscaEntities()
            : base("name=rawscaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<qr_shipping_log_mod> qr_shipping_log_mod { get; set; }
        public virtual DbSet<qr_shipping_log_org> qr_shipping_log_org { get; set; }
    }
}
