//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qr_shp_Log
{
    using System;
    using System.Collections.Generic;
    
    public partial class qr_shipping_log_mod
    {
        public int ID { get; set; }
        public int SEQ { get; set; }
        public int LOGIN_ID { get; set; }
        public System.DateTime TR_DATE_YMD { get; set; }
        public int TRUCK_NO { get; set; }
        public int CUST_NO { get; set; }
        public string TAG_TYPE { get; set; }
        public string P_N { get; set; }
        public string CUST_P_N { get; set; }
        public string QTY { get; set; }
        public string TAG_SEQ { get; set; }
        public System.DateTime SCAN_DATE_YMD { get; set; }
        public bool Status { get; set; }
        public string uuid { get; set; }
    }
}
